
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`include "fpga/MemSubSys.v"
`include "fpga/util/Synchronizer.v"

module DE2_115(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7,

	//////////// PS2 for Keyboard and Mouse //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// VGA //////////
	output		     [7:0]		VGA_B,
	output		          		VGA_BLANK_N,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

  // ---------------------------------------------------------------------
  // Generate clocks using Altera's Clock Source IP
  // ---------------------------------------------------------------------

  logic clk_100m;
  logic clk_25m;

  clk_gen clock_generator (
	.clk_clk           (CLOCK_50),
	.reset_reset_n     (1'b1),
	.clk_25m_clk       (clk_25m),
	.clk_100m_clk      (clk_100m)
  );

  // ---------------------------------------------------------------------
  // Synchronize Reset
  // ---------------------------------------------------------------------

  logic rst_25m;
  Synchronizer rst_sync (
	.clk (clk_25m),
	.in  (~KEY[0]),
	.out (rst_25m)
  );

  // ---------------------------------------------------------------------
  // Memory Subsystem
  // ---------------------------------------------------------------------

  MemIntf #( 8 ) imem();
  MemIntf #( 8 ) dmem();
  
  assign imem.req_val  = 1'b0;
  assign imem.req_msg  = '0;
  assign imem.resp_rdy = 1'b1;
  assign dmem.req_val  = 1'b0;
  assign dmem.req_msg  = '0;
  assign dmem.resp_rdy = 1'b1;

  logic [3:0] VGA_R_HIGH;
  logic [3:0] VGA_G_HIGH;
  logic [3:0] VGA_B_HIGH;

  MemSubSys #(
	.p_opaq_bits (8)
  ) memory_subsys (
	.clk     (clk_25m),
	.rst     (rst_25m),
	.mem_clk (clk_100m),
	
	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	// Memory Interfaces
	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	
	.imem (imem),
	.dmem (dmem),

	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	// SPI Interface
	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	.cs      (GPIO[0]),
	.miso    (),
	.mosi    (GPIO[2]),
	.sclk    (GPIO[3]),

	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	// PS2 Interface
	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	.PS2_CLK  (PS2_CLK),
	.PS2_DATA (PS2_DAT),
	
	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
	// VGA Interface
	// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

	.VGA_BLANK_N (VGA_BLANK_N),
	.VGA_SYNC_N  (VGA_SYNC_N),
	.VGA_HS      (VGA_HS),
	.VGA_VS      (VGA_VS),
	.VGA_R       (VGA_R_HIGH),
	.VGA_G       (VGA_G_HIGH),
	.VGA_B       (VGA_B_HIGH)
  );

  assign VGA_R = { VGA_R_HIGH, 4'b0 };
  assign VGA_G = { VGA_G_HIGH, 4'b0 };
  assign VGA_B = { VGA_B_HIGH, 4'b0 };
  assign VGA_CLK = clk_25m;
  
  assign HEX0[0] = GPIO[0];
  assign HEX0[2] = GPIO[2];
  assign HEX0[3] = GPIO[3];

endmodule
