#!/usr/bin/env bash
#=========================================================================
# 00-artisan-sramgen
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Determine RUNDIR and SRCDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"

cd $RUNDIR

# Copy SRAMs

cp ${TSMC_180NM}/srams/* .
