//========================================================================
// add_test_cases
//========================================================================
// Adapted from Cornell's ECE 2300

//------------------------------------------------------------------------
// test_case_golden_mixed_1_basic - generated by ChatGPT
//------------------------------------------------------------------------

task test_case_golden_mixed_1_basic();
  h.t.test_case_begin( "test_case_golden_mixed_1_basic" );
  if( !h.t.run_test ) return;
  fl_reset();

  // Write assembly program into memory


  h.asm( 'h200, "addi x10, x0, 256"      ); // x10 = 0x100 (data base)
  h.asm( 'h204, "addi x1,  x0, 7"        ); // x1 = 7
  h.asm( 'h208, "addi x2,  x0, 3"        ); // x2 = 3
  h.asm( 'h20c, "mul  x3,  x1, x2"       ); // x3 = 21
  h.asm( 'h210, "sw   x3,  0(x10)"       ); // mem[0x100] = 21
  h.asm( 'h214, "lw   x4,  0(x10)"       ); // x4 = 21
  h.asm( 'h218, "addi x5,  x0, 21"       ); // x5 = 21
  h.asm( 'h21c, "bne  x4,  x5, 0x234"    ); // if mismatch -> fail
  h.asm( 'h220, "addi x6,  x0, 0"        ); // x6 = 0

  // loop @ 0x224
  h.asm( 'h224, "addi x6,  x6, 1"        ); // x6++
  h.asm( 'h228, "blt  x6,  x2, 0x224"    ); // loop while x6 < 3

  h.asm( 'h22c, "jal  x7,  0x238"        ); // jump to done, x7 = 0x230
  h.asm( 'h230, "addi x9,  x0, 0"        ); // skipped

  // fail @ 0x234
  h.asm( 'h234, "addi x8,  x0, 1"        ); // error flag (should not execute)

  // done @ 0x238
  h.asm( 'h238, "or   x11, x4, x6"       ); // x11 = 21 | 3 = 23
  h.asm( 'h23c, "add  x0,  x0, x0"       ); // nop/end

  h.check_traces();

  h.t.test_case_end();
endtask

//------------------------------------------------------------------------
// run_add_tests
//------------------------------------------------------------------------

task run_golden_mixed_tests();
  test_case_golden_mixed_1_basic();
endtask
